version: '3.8'

services:

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64 # Comment this line if not using ARM architecture
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api:/app/api
    command: uvicorn api.main:app --host 0.0.0 --port 8000 --reload

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
#      - db_data:/var/lib/postgresql/data
      - ./api/db_init:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d mydatabase" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

#volumes:
#  db_data: